language: python

python:
  - 3.6

services:
  - postgresql

addons:
  postgresql: "10.4"

env:
  - DJANGO=1.11.15

before_install:
  - export DJANGO_SETTINGS_MODULE=fantasy.settings.dev
  - export PYTHONPATH=$HOME/builds/shlinx/fantasy
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install
  - pip install django==$DJANGO --quiet

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate --noinput

script:
  - python manage.py test